APOD_IMAGES_SUBDIR = 'apod_nasa'
DEFAULT_APOD_NASA_COUNT = 30
DEFAULT_DELAY_IN_SECONDS = 14400
DEFAULT_EPIC_NASA_COUNT = 5
DEFAULT_IMAGES_DIRECTORY = 'images'
EPIC_IMAGES_SUBDIR = 'epic_nasa'
SPACEX_IMAGES_SUBDIR = 'spacex'